# DataSource Config
spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.249.4:8848
    gateway:
      routes:
        - id: coupon    #优惠券服务
          uri: lb://coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: member    #会员服务
          uri: lb://member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: order    #订单服务
          uri: lb://order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: product    #商品服务
          uri: lb://product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: ware    #仓储服务
          uri: lb://ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: admin    #后台服务
          uri: lb://admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}
server:
  port: 88
logging:
  level:
    org.springframework.cloud.gateway: debug