spring:
  cloud:
    gateway:
      routes:
        - id: product-route
          uri: lb://gulimail-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
        - id: coupon-route
          uri: lb://gulimail-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
        - id: member-route
          uri: lb://gulimail-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
        - id: order-route
          uri: lb://gulimail-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
        - id: ware-route
          uri: lb://gulimail-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
        - id: thirdParty-route
          uri: lb://gulimail-third-party
          predicates:
            - Path=/api/thirdParty/**
          filters:
            - RewritePath=/api/thirdParty/(?<segment>/?.*),/$\{segment}
        - id : admin-route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters :
            - RewritePath=/api/(?<segment>/?.*),/renren-fast/$\{segment}
