# DataSource Config
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.249.4:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.249.4:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    com.alibaba.cloud.nacos.client: debug
    org.sysu.rain.Mapper: debug
    com.kaven.mybatisplus.dao: trace
  pattern:
    console: '%p%m%n'

mybatis-plus:
  #配置mapper.xml扫描路径
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      #配置数据库主键 自增
      id-type: auto

